branch-defaults:
  default:
    environment: banking-buddy-dev-user-env
environment-defaults:
  banking-buddy-dev-user-env:
    branch: null
    repository: null
global:
  application_name: banking-buddy-dev-user-service
  default_ec2_keyname: null
  default_platform: Corretto 21 running on 64bit Amazon Linux 2023
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
